Add 2048.cpp
up-for-grabs/up-for-grabs.net pull request #1007
Opened 2018-10-01 17:38 UTC by plibither8

2018-10-03 18:51 UTC, ritwik12 commented
@plibither8 I guess .cpp in your file name is causing problems.

2018-10-03 19:15 UTC, plibither8 commented
@ritwik12 what about now?

2018-10-04 10:23 UTC, ritwik12 requested changes

2018-10-04 10:23 UTC, ritwik12 commented on _data/projects/2048-cpp.yml
> +  link: https://github.com/plibither8/2048.cpp/issues
@plibither8 Please create a label with name "help needed" in your repo and mark some issues with that label. Otherwise use some other label name like "good first issue" or "help wanted"

2018-11-25 08:06 UTC, ritwik12 commented
@plibither8 Ping

2018-11-25 08:15 UTC, plibither8 commented
Hi! As of now the repo has 8 active issues with two of them marked as `good-first-issue` and 3 as `help-wanted`. I think this fits the criteria.

2018-11-25 08:18 UTC, closed without merging

2018-11-25 15:46 UTC, ritwik12 commented on _data/projects/2048-cpp.yml
> +  name: help needed
@plibither8 Please change this to either "help wanted" or "good first issue".

2018-11-25 15:46 UTC, ritwik12 commented on _data/projects/2048-cpp.yml
> +  link: https://github.com/plibither8/2048.cpp/issues
@ Please change this to "https://github.com/plibither8/2048.cpp/labels/help%20wanted" or "https://github.com/plibither8/2048.cpp/labels/good%20first%20issue" based on the name that you are choosing above.

2018-11-25 15:47 UTC, ritwik12 commented
@plibither8 Please make these changes and I will merge it asap. Thanks !!

2018-11-25 15:49 UTC, plibither8 commented
Hi @ritwik12, I had deleted my fork of the repo, so I'm unable to make any changes to that now. I don't know how to go about it.