Add the po4a project
up-for-grabs/up-for-grabs.net pull request #1022
Opened 2018-10-04 12:18 UTC by mquinson

This is a follow up of #1018.

2018-10-05 15:59 UTC, ritwik12 requested changes

2018-10-05 15:59 UTC, ritwik12 commented on _data/projects/po4a.yml
> +  link: https://github.com/mquinson/po4a/issues?q=is%3Aissue+is%3Aopen+label%3A%22beginner+friendly%22
@mquinson Please change this to "https://github.com/mquinson/po4a/labels/beginner%20friendly"

2018-10-07 19:19 UTC, mquinson commented
Hello,

I used the online editor to create the PR, without forking the repo. Unfortunately, I cannot edit the file, I can only create another PR. It seems more efficient to me if you merge this request so that I can edit the resulting file instead of restarting from scratch in a third PR.

But I'll create another PR if you prefer me to.

Thanks for your time, Mt.

2018-10-07 19:51 UTC, ritwik12 approved these changes

2018-10-07 19:52 UTC, ritwik12 commented
@mquinson That's fine. thanks for letting me know. I am making the correction for you after merging this.

2018-10-07 19:52 UTC, merged

2018-10-07 20:00 UTC, mquinson commented
It seems that you can see when people are using this feature because the PR is marked as coming from `unknown repository` at the top of the page. 

Thanks for your understanding.

2018-10-07 20:11 UTC, ritwik12 commented
@mquinson Your welcome, but whenever we use online editor then github creates a fork for that itself and all the changes made are stored in that fork. Why not here?