Adds algorithms-js as a project
up-for-grabs/up-for-grabs.net pull request #1029
Opened 2018-10-07 08:28 UTC by manrajgrover

This PR adds `algorithms-js` as a project.

2018-10-07 20:24 UTC, ritwik12 requested changes

2018-10-07 20:24 UTC, ritwik12 commented on _data/projects/algorithms-js.yml
> +  name: up-for-grabs
@manrajgrover Please change this to "good first issue" as your label link is for that tag only.

2018-10-08 17:29 UTC, manrajgrover commented on _data/projects/algorithms-js.yml
> +  name: up-for-grabs
@ritwik12 Thanks for catching that. Should be fixed now

2018-10-09 19:43 UTC, ritwik12 approved these changes

2018-10-09 19:43 UTC, merged

2018-10-09 19:43 UTC, ritwik12 commented
@manrajgrover Thanks!!