Sharing A Project
up-for-grabs/up-for-grabs.net pull request #1051
Opened 2018-10-16 23:31 UTC by Cyclostone

The shared project is a successful project done by Team Venom, And has a lot of potentials to save a lot of lives

2018-10-17 12:10 UTC, ritwik12 requested changes

2018-10-17 12:10 UTC, ritwik12 commented on snake_bot.yml
> +site: No Site yet
@Cyclostone You can give the link to your project repo.

2018-10-17 12:10 UTC, ritwik12 commented on snake_bot.yml
> +  link: https://github.com/Cyclostone/project/labels/up%20for%20grabs
@Cyclostone This link is invalid

2018-10-17 12:10 UTC, ritwik12 commented on snake_bot.yml
> +tags:
Mention languages used too

2019-02-11 17:38 UTC, shiftkey commented
Closing this out due to inactivity.

@Cyclostone once you have a project up and running, feel free to submit a listing again that Up for Grabs can point to.

2019-02-11 17:38 UTC, closed without merging