Create atom-icons.yml
up-for-grabs/up-for-grabs.net pull request #1075
Opened 2018-10-28 15:58 UTC by haideralipunjabi

2018-10-29 18:26 UTC, ritwik12 requested changes

2018-10-29 18:26 UTC, ritwik12 commented on _data/projects/atom-icons.yml
> +  link: https://github.com/HackeSta/atom-icons/issues?q=is%3Aissue+is%3Aopen+label%3A"help+wanted"
@haideralipunjabi Please change this to https://github.com/HackeSta/atom-icons/labels/help%20wanted

2018-10-30 12:07 UTC, haideralipunjabi commented
Done

2018-10-30 16:24 UTC, ritwik12 approved these changes

2018-10-30 16:24 UTC, merged

2018-10-30 16:24 UTC, ritwik12 commented
@haideralipunjabi Thanks!!