Adds wemake-python-styleguide
up-for-grabs/up-for-grabs.net pull request #1103
Opened 2018-12-07 08:21 UTC by sobolevn

https://github.com/wemake-services/wemake-python-styleguide

2018-12-08 19:13 UTC, ritwik12 requested changes

2018-12-08 19:13 UTC, ritwik12 commented on _data/projects/wemake-python-styleguide.yml
> +  link: https://github.com/wemake-services/wemake-python-styleguide/issues?q=is%3Aissue+is%3Aopen+label%3Alevel%3Astarter
@sobolevn Please change this to "https://github.com/wemake-services/wemake-python-styleguide/labels/level%3Astarter"

2018-12-08 19:13 UTC, ritwik12 commented on _data/projects/wemake-python-styleguide.yml
> +site: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md
@sobolevn Please make this as your repo link i.e "https://github.com/wemake-services/wemake-python-styleguide"

2018-12-08 21:44 UTC, sobolevn commented
@ritwik12 fixed, thanks!

2018-12-14 07:52 UTC, sobolevn commented
@ritwik12 friendly ping 🙂

2018-12-15 16:25 UTC, ritwik12 commented
@sobolevn Thanks for the ping. I am so sorry for the delay. Was busy and then missed your PR.

2018-12-15 16:25 UTC, ritwik12 approved these changes

2018-12-15 16:25 UTC, merged

2018-12-15 16:25 UTC, ritwik12 commented
@sobolevn Thanks!!