Add Spruce
up-for-grabs/up-for-grabs.net pull request #1224
Opened 2019-05-18 16:16 UTC by DivySrivastava

Spruce is a tiny but powerful open-source social networking platform made with Node.js and MongoDB.

Thank You!

2019-05-19 11:54 UTC, ritwik12 requested changes

2019-05-19 11:54 UTC, ritwik12 commented on _data/projects/Spruce.yml
> +  name: beginner
@DivySrivastava  Here, you should have the name for the label that you want to use to label your issues, such as "good first issue", "help wanted", "up-for-grabs", etc.

2019-05-19 11:54 UTC, ritwik12 commented on _data/projects/Spruce.yml
> +  link: https://github.com/DivySrivastava/spruce
Give the link to your label that you want to use, for example - https://github.com/DivySrivastava/spruce/labels/good%20first%20issue

2019-05-19 11:55 UTC, ritwik12 commented
@DivySrivastava Also, tag your issues with the label that you have defined.

2019-05-19 13:23 UTC, DivySrivastava commented
Done! Thanks for the suggestions

2019-05-19 17:51 UTC, ritwik12 commented on _data/projects/Spruce.yml
> +  name: beginner
@DivySrivastava you haven't yet changed name for the label. I can see that you've used good first issue label link. if you are using that then give same name here also

2019-05-19 17:52 UTC, ritwik12 commented
@DivySrivastava Please make changes

2019-05-22 11:28 UTC, DivySrivastava commented
Done

2019-05-23 12:34 UTC, ritwik12 approved these changes

2019-05-23 12:35 UTC, merged

2019-05-23 12:35 UTC, ritwik12 commented
@DivySrivastava Thanks!!