Introduce gnome-sound-recorder
up-for-grabs/up-for-grabs.net pull request #1388
Opened 2019-09-30 20:54 UTC by gaurav1999

Gnome-sound recorder is one the well maintained and active project from GNOME developers, it's  nice start for one wishing to get started with FOSS, might be a good idea to add it to this list.

Thanks.

2019-09-30 20:56 UTC, gaurav1999 commented
@bilelmoussaoui , would like to know your view on the tags and description used. 

Thanks.

2019-09-30 20:57 UTC, bilelmoussaoui commented
@gaurav1999 Perfect. Thanks!

2019-09-30 22:00 UTC, ritwik12 requested changes

2019-09-30 22:00 UTC, ritwik12 commented on _data/gnome-sound-recorder.yml
> +  link: https://gitlab.gnome.org/GNOME/gnome-sound-recorder/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=4.%20Newcomers
@gaurav1999 Hey, I don't see any open issues with this label there, It is good to have some open tasks/ issues for contributors to work on. Please add some tasks or use some other label.

2019-09-30 22:00 UTC, ritwik12 commented on _data/gnome-sound-recorder.yml
> +
Please remove these extra lines.

2019-09-30 22:21 UTC, bilelmoussaoui commented on _data/gnome-sound-recorder.yml
> +  link: https://gitlab.gnome.org/GNOME/gnome-sound-recorder/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=4.%20Newcomers
I have added two for now. I will look into adding more tomorrow. Thanks!

2019-10-01 09:06 UTC, ritwik12 commented on _data/gnome-sound-recorder.yml
> +  link: https://gitlab.gnome.org/GNOME/gnome-sound-recorder/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=4.%20Newcomers
Thanks

2019-10-01 09:07 UTC, ritwik12 commented on _data/gnome-sound-recorder.yml
> +
@gaurav1999

2019-10-01 11:18 UTC, shiftkey requested changes
@gaurav1999 this project needs to be located in the `_data/projects/` directory for it to detected (it's currently only under `_data/`)

2019-10-01 19:26 UTC, gaurav1999 commented on _data/gnome-sound-recorder.yml
> +
Should be fine now, sorry missed to add these lines while raising a PR that time, thanks for review.

2019-10-01 19:27 UTC, gaurav1999 commented
@shiftkey , yes missed it because of my ide :/ , updated the location of file, I guess should be fine now. 
Thanks for review.

2019-10-01 19:42 UTC, shiftkey approved these changes

2019-10-02 07:52 UTC, ritwik12 approved these changes
lgtm!!

2019-10-02 07:52 UTC, merged

2019-10-02 07:53 UTC, ritwik12 commented
@gaurav1999 Thanks!!