Updated tldr-pages.yml
up-for-grabs/up-for-grabs.net pull request #1449
Opened 2019-10-06 20:35 UTC by filipe-gomes

Added mention to hacktoberfest, removed "help wanted."

2019-10-06 20:42 UTC, shiftkey requested changes

2019-10-06 20:42 UTC, shiftkey commented on _data/projects/tldr-pages.yml
> +  name: Hacktoberfest
This value is case-sensitive when looking for it using the GitHub API, so we need it to match:

```suggestion
  name: hacktoberfest
```

2019-10-07 12:12 UTC, shiftkey commented
It looks like the renamed project (no diff displaying) has `Help wanted` as the label, but it should be `help wanted`:

https://github.com/up-for-grabs/up-for-grabs.net/blob/a20c8e81698aaec96e00161813204d74459fe139/_data/projects/COMP30022-frontend.yml#L11-L12

2019-10-07 12:41 UTC, filipe-gomes commented
Thanks, I will fix that in the PR.

On Mon, Oct 7, 2019 at 7:12 AM Brendan Forster <notifications@github.com>
wrote:

> It looks like the renamed project (no diff displaying) has Help wanted as
> the label, but it should be help wanted:
>
>
> https://github.com/up-for-grabs/up-for-grabs.net/blob/a20c8e81698aaec96e00161813204d74459fe139/_data/projects/COMP30022-frontend.yml#L11-L12
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/up-for-grabs/up-for-grabs.net/pull/1449?email_source=notifications&email_token=AKA23PFTVYQECYMSVE2T4BDQNMRS5A5CNFSM4I55UP2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAQC4XI#issuecomment-538979933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKA23PBR23CV767DNCEEHNDQNMRS5ANCNFSM4I55UP2A>
> .
>

2019-10-07 13:00 UTC, shiftkey approved these changes
Thanks @filipe-gomes!

2019-10-07 13:01 UTC, merged

2019-10-07 20:23 UTC, shiftkey commented
@all-contributors please add @filipe-gomes for content