Added PyTorch
up-for-grabs/up-for-grabs.net pull request #1452
Opened 2019-10-07 03:52 UTC by sangy987

2019-10-07 12:17 UTC, shiftkey requested changes

2019-10-07 12:17 UTC, shiftkey commented on _data/projects/.yml
> +  link: https://github.com/up-for-grabs/up-for-grabs.net/labels/up-for-grabs
This link is a URL for Up for Grabs itself - do you have a corresponding link for `pytorch/pytorch` that represents a list of issues that are ideal for new contributors?

2019-10-07 12:18 UTC, shiftkey commented
The new file is not named correctly, which is causing CI to fail. And an existing project has been removed from the list - please restore that.

2019-10-08 09:18 UTC, ritwik12 commented
@sangy987 Closing it out for #1473

2019-10-08 09:18 UTC, closed without merging