Solving no var violation by changing 'var' to 'let' in javascripts/main.js
up-for-grabs/up-for-grabs.net pull request #1523
Opened 2019-10-11 19:32 UTC by XxZhang2017

I have updated javascripts/main.js.

2019-10-11 21:10 UTC, shiftkey requested changes
This all looks good aside from the middle, because we'd put `count` (which may update based on what it finds) alongside two other variables that don't need to change.

I think the suggested changes should do it, but we might need another round of review after applying those.

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +    const a = $(project).find('.label a'),
```suggestion
    const a = $(project).find('.label a');
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
>        gh = a
```suggestion
      const gh = a
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
>          .match(/github.com(\/[^\/]+\/[^\/]+\/)(?:issues\/)?labels\/([^\/]+)$/),
```suggestion
        .match(/github.com(\/[^\/]+\/[^\/]+\/)(?:issues\/)?labels\/([^\/]+)$/);
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +      counthref = a.find('.count');
```suggestion
      let count = a.find('.count');
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +    if (counthref.length) {
```suggestion
    if (count.length) {
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +      countspantitle = $(
```suggestion
      count = $(
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +    countspanimg = $(
```suggestion
    count = $(
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +        countspanimg.html(resultCount);
```suggestion
        count.html(resultCount);
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +        countspanimg.html('?!');
```suggestion
        count.html('?!');
```

2019-10-11 21:10 UTC, shiftkey commented on javascripts/main.js
> +        countspanimg.attr('title', message);
```suggestion
        count.attr('title', message);
```

2019-10-13 05:55 UTC, XxZhang2017 commented
@shiftkey The reason that I change it is as follow. The pre-const rules failed it if issueCount, a, gh are let. It suggests changing to const. In this case, count is reassigned the value which is complained by the ESlint. The message isreassigned value to the const.
` count = a.find('.count');

    if (count.length) {
      return;
    }

    if (!gh) {
      count = $(
        '<span class="count" title="Issue count is only available for projects on GitHub.">?</span>'
      ).appendTo(a);
      return;
    }

    count = $(
      '<span class="count"><img src="images/octocat-spinner-32.gif" /></span>'
    ).appendTo(a);

    const ownerAndName = gh[1];
    const labelEncoded = gh[2];

    fetchIssueCount(ownerAndName, labelEncoded).then(
      resultCount => {
        count.html(resultCount);
      },
      error => {
        const message = error.message ? error.message : error;
        count.html('?!');
        count.attr('title', message);
      }`

2019-10-13 14:07 UTC, shiftkey commented
> Any other suggestions to do it I am happy to think about it.

We need to refactor this single `var` into three `var` statements, and restore the names to what they were before: 

```js
const issueCount = function(project) {
    var a = $(project).find('.label a');
    var gh = a
      .attr('href')
      .match(/github.com(\/[^\/]+\/[^\/]+\/)(?:issues\/)?labels\/([^\/]+)$/);
    var count = a.find('.count');

    if (count.length) {
      return;
    }

    if (!gh) {
      count = $(
        '<span class="count" title="Issue count is only available for projects on GitHub.">?</span>'
      ).appendTo(a);
      return;
    }

    count = $(
      '<span class="count"><img src="images/octocat-spinner-32.gif" /></span>'
    ).appendTo(a);

    const ownerAndName = gh[1];
    const labelEncoded = gh[2];

    fetchIssueCount(ownerAndName, labelEncoded).then(
      resultCount => {
        count.html(resultCount);
      },
      error => {
        const message = error.message ? error.message : error;
        count.html('?!');
        count.attr('title', message);
      }
    );
  };
``` 

Now, when you run `npm run lint-fix` it'll detect that the first two are unused (changing them to `const`) and the last one is updated (changing it to `let`):

```js
const issueCount = function(project) {
    const a = $(project).find('.label a');
    const gh = a
      .attr('href')
      .match(/github.com(\/[^\/]+\/[^\/]+\/)(?:issues\/)?labels\/([^\/]+)$/);
    let count = a.find('.count');

    if (count.length) {
      return;
    }

    if (!gh) {
      count = $(
        '<span class="count" title="Issue count is only available for projects on GitHub.">?</span>'
      ).appendTo(a);
      return;
    }

    count = $(
      '<span class="count"><img src="images/octocat-spinner-32.gif" /></span>'
    ).appendTo(a);

    const ownerAndName = gh[1];
    const labelEncoded = gh[2];

    fetchIssueCount(ownerAndName, labelEncoded).then(
      resultCount => {
        count.html(resultCount);
      },
      error => {
        const message = error.message ? error.message : error;
        count.html('?!');
        count.attr('title', message);
      }
    );
  };
```

2019-10-14 00:48 UTC, XxZhang2017 commented
@shiftkey Thank you for the explaining. I committed  the changes. Is everything ok now ?

2019-10-14 12:04 UTC, shiftkey requested changes
Almost there - just one more change and then run `npm run prettier-fix` and commit the cleanup.

2019-10-14 12:04 UTC, shiftkey commented on javascripts/main.js
> +      counthref = a.find('.count');
```suggestion
      let count = a.find('.count');
```

2019-10-14 21:21 UTC, XxZhang2017 commented
@shiftkey could you give me a moment? let me fix it.

2019-10-14 21:22 UTC, shiftkey commented
@XxZhang2017 you're close - just need to do this bit:

> then run `npm run prettier-fix` and commit the cleanup.

2019-10-14 21:52 UTC, XxZhang2017 commented
@shiftkey Hi, may I ask a question ?  I have trouble synchronize the fork project with the original one.

2019-10-15 06:28 UTC, XxZhang2017 commented
@ shiftkey I am sorry that there is issue. The picture shows what I did. I think it should be fine.
<img width="963" alt="Screen Shot 2019-10-14 at 11 26 30 PM" src="https://user-images.githubusercontent.com/26696836/66805548-286ca200-eeda-11e9-8d66-bb7c7e7d21b4.png">

2019-10-15 07:30 UTC, XxZhang2017 commented
@ shiftkey I am sorry that there is still issue. But I have run it. I have no idea what is wrong with it.

<img width="963" alt="Screen Shot 2019-10-14 at 11 26 30 PM" src="https://user-images.githubusercontent.com/26696836/66809686-b3519a80-eee2-11e9-8106-66fcf1fe9577.png">
It passed the check here. 
<img width="765" alt="Screen Shot 2019-10-15 at 12 28 59 AM" src="https://user-images.githubusercontent.com/26696836/66809766-dbd99480-eee2-11e9-99f4-bd5c204f1b10.png">
Anything I can do at this point ?

2019-10-15 09:11 UTC, shiftkey commented
@XxZhang2017 ensure you are running the command in your `edit-ESLint` branch (screenshot seems to suggest you're on the `gh-pages` branch)

2019-10-17 12:21 UTC, shiftkey approved these changes

2019-10-17 12:21 UTC, shiftkey commented
@XxZhang2017 thanks!

2019-10-17 12:21 UTC, shiftkey commented
@all-contributors please add @XxZhang2017 for code

2019-10-17 12:21 UTC, merged