Create legesher.yml
up-for-grabs/up-for-grabs.net pull request #1558
Opened 2019-10-15 08:02 UTC by Beomus

2019-10-15 09:19 UTC, shiftkey requested changes
@nemequ thanks for submitting!

Please rename `legesher.yml` to `_data/projects/legesher.yml` so that it will be listed on the site, and there's also some suggested changes I have to get this ready to merge.

2019-10-15 09:19 UTC, shiftkey commented on legesher.yml
> +  name: help needed with various projects
This field needs to match with the label used in the project:

```suggestion
  name: Good First Issue
```

2019-10-15 09:19 UTC, shiftkey commented on legesher.yml
> +- html/css
This value should be split into two separate values:

```suggestion
- html
- css
```

2019-10-16 12:16 UTC, Beomus commented
Thank you for your review! I have made changes according to your suggestions, please let me know if you need me to change anything else.

2019-10-16 12:29 UTC, shiftkey requested changes
Very close -  just ensuring the label name matches what's in use

2019-10-16 12:29 UTC, shiftkey commented on _data/projects/legesher.yml
> +  link: https://github.com/legesher/legesher/labels/Good%20First%20Issue
```suggestion
  link: https://github.com/legesher/legesher/labels/good%20first%20issue
```

2019-10-16 12:29 UTC, shiftkey commented on _data/projects/legesher.yml
> +  name: Good First Issue
```suggestion
  name: good first issue
```

2019-10-16 12:46 UTC, shiftkey approved these changes

2019-10-16 12:46 UTC, shiftkey commented
Thanks @Beomus!

2019-10-16 12:48 UTC, merged