First ML project
up-for-grabs/up-for-grabs.net pull request #1608
Opened 2019-10-22 17:34 UTC by snehit31

Hi This is an update for all ML,data scientist enthusiast.

2019-10-22 21:21 UTC, shiftkey requested changes

2019-10-22 21:21 UTC, shiftkey commented on _data/projects/ML
> +site: datascience.com/highest-rated-ml-projects-on-github-694486293
Is this link correct? For me it redirects to `https://www.oracle.com/corporate/acquisitions/datascience/` which doesn't seem relevant.

2019-10-22 21:21 UTC, shiftkey commented on _data/projects/ML
> +  link: https://github.com/snehit31/up-for-grabs.net
This is your fork of the Up for Grabs repository.

2019-10-22 21:21 UTC, shiftkey commented on _data/projects/ML
> +  name: Sexiest Job 21st Century
I hope this is not a real label you plan to use

2019-10-22 21:23 UTC, shiftkey commented
@snehit31 you have currently opened six pull requests against the project in the last 48 hours - #1593 #1594 #1595 #1596 #1608 #1609 - and the details in this one make me question whether you are looking at the review feedback and want to actually list some projects, and are instead just opening pull requests to try and achieve some goal.

I don't want to ban anyone from this project, but my tolerance of his behaviour has hit it's limit.

**This is your first official warning. Please stop opening new pull requests, and either address or close the pull requests you have previously opened before opening any more. If you continue to open pull requests I will block you from this project.**

@snehit31 please confirm you understand what I am saying and why I am saying it.

2019-10-23 03:42 UTC, snehit31 commented
Yes sir,I understood your concern and apologize for this behaviour.Actually it was my first repository on which I was working and I was just experimenting to understand.I would'nt be making any more pull request.

2019-10-23 07:55 UTC, closed without merging