Improve hover on button and h1 readablility
up-for-grabs/up-for-grabs.net pull request #1642
Opened 2019-10-28 09:29 UTC by sajadhussain

I have just improved the readability of heading as well as a made href more interactive.

2019-10-28 09:37 UTC, sajadhussain commented
Improvement in readibility

2019-10-30 17:31 UTC, ritwik12 commented
@sajadhussain Would like to keep the h1 as original only and please remove that change from this PR. I would like to keep hover in this PR as it looks good. @shiftkey Hover looks good but you can decide the exact px and size of hover.

2019-10-30 17:31 UTC, ritwik12 requested changes

2019-10-30 17:31 UTC, ritwik12 commented on stylesheets/stylesheet.css
> +  font-size: 58px;
@sajadhussain Please remove this as it is not having any valid changes.

2019-10-30 17:45 UTC, sajadhussain commented on stylesheets/stylesheet.css
> +  font-size: 58px;
okay got

2019-10-30 17:49 UTC, shiftkey commented
> @shiftkey Hover looks good but you can decide the exact px and size of hover.

@ritwik12 @sajadhussain I'm curious what problem we're trying to address here with this change. I can see what's changed but I'd like to understand _why_ we're doing it this way, as we might be able to provide useful feedback about the changes or suggest a better solution.

2019-11-02 00:32 UTC, ritwik12 commented
@sajadhussain Please let us know what problems it will solve and why is it needed. Better to have an issue for this to discuss further.

2019-11-02 11:01 UTC, sajadhussain commented
It is UX improvement of the site. Just improve the button. code hover so it will more interactive and give a sense of working.

2019-11-26 20:07 UTC, ritwik12 commented
@sajadhussain Thanks for your PR, it might seem good but is not that much needed here as the primitive site looks good in itself.

We have many issues that need attention and would be happy if you can help there based on your skills. like #930, etc

@shiftkey Please feel free to give your thoughts here

2019-11-27 14:30 UTC, shiftkey commented
> Please feel free to give your thoughts here

There's a few things I don't like about this PR, and I've tried to capture this in a GIF so you can see it for yourself:

 - when you hover over the button, the text alongside it gets nudged down slightly because of the padding changes. 

![](https://user-images.githubusercontent.com/359239/69730767-0aac7280-10ff-11ea-8b81-1d5244173983.gif)

 - making the font size slightly bigger at the same time feels a bit jarring

 - this solution leverages `:hover`, which is only available for desktop users - what about mobile users, or users with screen readers?

> It is UX improvement of the site. Just improve the button. code hover so it will more interactive and give a sense of working.

In situations like this I'd prefer to discuss the problem through an issue, rather than going straight to a proposed solution using a pull request. The underlying problem is still unclear to me, and I believe using animations like this for web pages should only occur when absolutely necessary.

If we've got a good grasp on the problem and nothing else seems suitable, then I'm fine to revisit this.

2019-11-27 14:30 UTC, closed without merging