Add PowerShell docker images project
up-for-grabs/up-for-grabs.net pull request #2067
Opened 2020-05-17 20:58 UTC by TravisEz13

2020-05-17 21:23 UTC, RDIL requested changes

2020-05-17 21:23 UTC, RDIL commented on _data/projects/powershell-docker.yml
> +desc: The docker images PowerShell releases, both official and communit.
```suggestion
desc: The docker images PowerShell releases, both official and community.
```

2020-05-17 21:25 UTC, TravisEz13 commented
Thanks for reviewing, @RDIL!

2020-05-17 21:25 UTC, RDIL approved these changes

2020-05-17 21:51 UTC, ritwik12 requested changes

2020-05-17 21:51 UTC, ritwik12 commented on _data/projects/powershell-docker.yml
> +  name: up for grabs
@TravisEz13 As per your Labe link and name of label in your Repo, this should be 'up-for-grabs'
```suggestion
  name: up-for-grabs
```

2020-05-17 22:13 UTC, ritwik12 requested changes

2020-05-17 22:13 UTC, ritwik12 commented on _data/projects/powershell-docker.yml
> +  link: https://github.com/powershell/powershell-docker/labels/up-for-grabs
@TravisEz13 Just crosschecked the label name on your repo and found out that it is 'Up-for-Grabs' and not 'up-for-grabs'. Hence, the reason for the build failures.
```suggestion
  link: https://github.com/PowerShell/PowerShell-Docker/labels/Up-for-Grabs
```

2020-05-17 22:13 UTC, ritwik12 commented on _data/projects/powershell-docker.yml
> +  name: up-for-grabs
```suggestion
  name: Up-for-Grabs
```

2020-05-25 18:30 UTC, ritwik12 commented
@TravisEz13 @RDIL Ping!!

2020-05-27 19:04 UTC, shiftkey approved these changes
Thanks for the contribution @TravisEz13!

2020-05-27 19:05 UTC, merged

2020-05-27 20:53 UTC, TravisEz13 commented
Thanks for being patient