Create PyConSys
up-for-grabs/up-for-grabs.net pull request #2085
Opened 2020-05-24 11:21 UTC by mck-sbs

Help wanted

2020-05-24 11:22 UTC, mck-sbs reviewed
file extansion fixed

2020-05-24 11:23 UTC, mck-sbs reviewed
Site fixed

2020-05-25 13:00 UTC, ritwik12 requested changes

2020-05-25 13:00 UTC, ritwik12 commented on _data/projects/PyConSys.yml
> +  link: https://github.com/mck-sbs/PyConSys/projects/1
@mck-sbs Please use this link `https://github.com/mck-sbs/PyConSys/labels/help%20wanted` for labels and also add issues in your Repo marked with this label.

2020-05-25 13:00 UTC, ritwik12 commented on _data/projects/PyConSys.yml
> +  - ai
@mck-sbs Add `artificial-intelligence` too to make it more searchable

2020-05-25 13:42 UTC, mck-sbs commented
Sorry, deleted my local repo. I started a new pull request. Thank you.

2020-05-25 13:42 UTC, closed without merging