Added GitGud
up-for-grabs/up-for-grabs.net pull request #2305
Opened 2020-09-14 14:54 UTC by H3RSKO

We are an actively managed project perfect for beginners. 

We are using ink (https://github.com/vadimdemedes/ink) which allows us to create a CLI tool using React components. Pretty cool!

2020-09-20 23:04 UTC, ritwik12 requested changes, later dismissed

2020-09-20 23:04 UTC, ritwik12 commented on _data/projects/GitGud.yaml
> +  link: https://github.com/GitGud-org/GitGud/projects/1?card_filter_query=label%3A%22good+first+issue%22
@H3RSKO Please use this link https://github.com/GitGud-org/GitGud/labels/good%20first%20issue

2020-09-21 02:12 UTC, H3RSKO commented
Updated the link

2020-09-22 17:08 UTC, shiftkey approved these changes

2020-09-22 17:08 UTC, merged