adding devdojo tails project
up-for-grabs/up-for-grabs.net pull request #2379
Opened 2020-10-04 07:04 UTC by ganapathi12

this project is very friendly for the first time contributors all you need to is add new components in tailwind css.
let me know if there's any feedback about the template.

2020-10-04 07:22 UTC, ganapathi12 commented
i am sorry to say this, but in the hactoberfest page i see that contributing to this repositery is ineligible (Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.), so could you please add "hacktoberfest" topic to your repository. @ritwik12 @kudoabhijeet

2020-10-06 19:22 UTC, ritwik12 requested changes

2020-10-06 19:22 UTC, ritwik12 commented on _data/projects/Devdojo_tails.yml
> +  link: https://github.com/thedevdojo/tails/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
@ganapathi12 Please use this instead https://github.com/thedevdojo/tails/labels/help%20wanted

2020-10-06 19:22 UTC, ritwik12 commented
> i am sorry to say this, but in the hactoberfest page i see that contributing to this repositery is ineligible (Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.), so could you please add "hacktoberfest" topic to your repository. @ritwik12 @kudoabhijeet @KirankumarAmbati @floydpink @luckyguy73

This is done!!

2020-10-07 01:39 UTC, ganapathi12 commented
Hi @ritwik12! the change you have suggested is done!

2020-10-07 01:51 UTC, ganapathi12 commented
> > i am sorry to say this, but in the hactoberfest page i see that contributing to this repositery is ineligible (Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.), so could you please add "hacktoberfest" topic to your repository. @ritwik12 @kudoabhijeet @KirankumarAmbati @floydpink @luckyguy73
> 
> This is done!!

And could you please add "hacktoberfest-accepted" label to my PR so that i can actively participate in hacktober fest! @ritwik12

2020-10-07 01:55 UTC, ganapathi12 reviewed
Changed the requested changes!

2020-10-07 19:26 UTC, ritwik12 requested changes

2020-10-07 19:26 UTC, ritwik12 commented on _data/projects/Devdojo_tails.yml
> +      It's pretty simple to use any of these components or templates in your project. Any component you wish to use can be copied and pasted into your own project. Visit the Components page to view t
@ganapathi12 I think we can remove this line to make the desc short.

2020-10-07 19:27 UTC, ritwik12 commented
> > > i am sorry to say this, but in the hactoberfest page i see that contributing to this repositery is ineligible (Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.), so could you please add "hacktoberfest" topic to your repository. @ritwik12 @kudoabhijeet @KirankumarAmbati @floydpink @luckyguy73
> > 
> > 
> > This is done!!
> 
> And could you please add "hacktoberfest-accepted" label to my PR so that i can actively participate in hacktober fest! @ritwik12

@ganapathi12 You would not need that as it will be merged after your corrections.

2020-10-08 01:32 UTC, ganapathi12 reviewed
@ritwik12 , updated requested changes!

2020-10-08 19:32 UTC, ritwik12 approved these changes

2020-10-08 19:32 UTC, merged

2020-10-08 19:32 UTC, ritwik12 commented
@ganapathi12 Thanks!!