Create owasp-vulnerableapp.yml
up-for-grabs/up-for-grabs.net pull request #2380
Opened 2020-10-04 07:43 UTC by preetkaran20

2020-10-04 07:55 UTC, preetkaran20 commented
Hi Team,

I have added the entries using up-for-grabs tool but that has not mentioned any validations like : is not allowed or space in tags is not allowed, lower-case letters are only allowed. can you guys please update the tool too to validate and also give some indication while taking the input so that raising PR's becomes more easier.

thanks,
Karan

2020-10-06 19:28 UTC, ritwik12 commented
@preetkaran20 By tool did you meant `Yeoman Generator`?

2020-10-06 19:30 UTC, ritwik12 requested changes

2020-10-06 19:30 UTC, ritwik12 commented on _data/projects/owasp-vulnerableapp.yml
> +  link: https://github.com/SasanLabs/VulnerableApp/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
@preetkaran20 Please use this instead https://github.com/SasanLabs/VulnerableApp/labels/good%20first%20issue

2020-10-06 19:30 UTC, ritwik12 commented on _data/projects/owasp-vulnerableapp.yml
> +desc: As Web Applications are becoming popular these days, there comes a dire need to secure them. Although there are several Vulnerability Scanning Tools, however while developing these tools, devel
@preetkaran20 I recommend having a short and crisp description. Can we please work on this?

2020-10-07 00:14 UTC, preetkaran20 commented
> @preetkaran20 By tool did you meant `Yeoman Generator`?

Yes

2020-10-07 01:33 UTC, preetkaran20 commented
Hi @ritwik12 ,

I have done the suggested change. Please review.

thanks,
Karan

2020-10-07 19:29 UTC, ritwik12 commented
> > @preetkaran20 By tool did you meant `Yeoman Generator`?
> 
> Yes

@preetkaran20 Please feel free to open an issue with what you faced and what should be there. We would be happy to get that sorted.

2020-10-07 19:29 UTC, ritwik12 approved these changes

2020-10-07 19:30 UTC, merged

2020-10-07 19:30 UTC, ritwik12 commented
@preetkaran20 Thanks!!