Added my project fibonacci-series.yml
up-for-grabs/up-for-grabs.net pull request #2387
Opened 2020-10-05 06:58 UTC by fharookshaik

Hi there!

I hope that my project will fit for the Up for grabs.

Please give any kind of feedback that you feel to improve my project.

Thank You

2020-10-06 19:34 UTC, ritwik12 requested changes

2020-10-06 19:34 UTC, ritwik12 commented on _data/projects/fibonacci-series.yml
> +  link: https://github.com/fharookshaik/fibonacci_series/labels/help%20wanted
@fharookshaik As per the name in line above the link should be https://github.com/fharookshaik/fibonacci-series/labels/up%20for%20grabs

2020-10-06 19:34 UTC, ritwik12 commented on _data/projects/fibonacci-series.yml
> +site: https://github.com/fharookshaik/fibonacci_series
@fharookshaik I believe you changed the Repo name to https://github.com/fharookshaik/fibonacci-series. please correct.

```suggestion
site: https://github.com/fharookshaik/fibonacci-series
```

2020-10-07 06:18 UTC, fharookshaik commented
Required changes have been made.

2020-10-07 19:28 UTC, merged

2020-10-07 19:28 UTC, ritwik12 commented
@fharookshaik Thanks!!