Adding couchers project
up-for-grabs/up-for-grabs.net pull request #2607
Opened 2021-03-07 23:36 UTC by ShmuelTreiger

We are looking for devs and already have tags for first issues. I think we're a great fit

2021-03-13 19:59 UTC, ritwik12 requested changes

2021-03-13 19:59 UTC, ritwik12 commented on _data/projects/couchers.yml
> +  link: https://github.com/Couchers-org/couchers/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
```suggestion
  link: https://github.com/Couchers-org/couchers/labels/good%20first%20issue
```
That would be better.

2021-03-14 17:41 UTC, ritwik12 approved these changes

2021-03-14 17:42 UTC, merged

2021-03-14 17:42 UTC, ritwik12 commented
@ShmuelTreiger Thanks!!

2021-03-14 19:18 UTC, ShmuelTreiger commented
Thank you for maintaining this project!

2021-03-14 19:31 UTC, ritwik12 commented
> Thank you for maintaining this project!

Your welcome :)