Add Eclipse OpenJ9 and Eclipse OMR projects
up-for-grabs/up-for-grabs.net pull request #2632
Opened 2021-03-18 02:16 UTC by AdamBrousseau

2021-03-18 02:34 UTC, hamedtayeban approved these changes

2021-03-19 19:42 UTC, ritwik12 requested changes

2021-03-19 19:42 UTC, ritwik12 commented on _data/projects/eclipse-omr.yaml
> +  link: https://github.com/eclipse/openj9/labels/good%20first%20issue
@AdamBrousseau You meant omr right?
```suggestion
  link: https://github.com/eclipse/omr/labels/good%20first%20issue
```

2021-03-19 22:46 UTC, AdamBrousseau commented on _data/projects/eclipse-omr.yaml
> +  link: https://github.com/eclipse/openj9/labels/good%20first%20issue
Good catch, thanks.

2021-03-23 19:55 UTC, ritwik12 approved these changes

2021-03-23 19:55 UTC, merged

2021-03-23 19:55 UTC, ritwik12 commented
@AdamBrousseau Thanks!!