Add the Openverse project
up-for-grabs/up-for-grabs.net pull request #2888
Opened 2021-09-17 19:15 UTC by zackkrida

Openverse is a search engine for openly-licensed media, part of the WordPress ecosystem.

As the project is comprised of 4 different repositories, I've used the following GitHub search result as the `upforgrabs` link. Please let me know if that is acceptable.

2021-09-20 17:55 UTC, ritwik12 commented
@zackkrida With that search link, we wont be able to update project stats for this project due to which we wont be able to show the number of open issues and last updated. Would be better if you can share the Github project link and issues link.

2021-10-01 15:39 UTC, zackkrida commented on _data/projects/Openverse.yml
> +  link: https://github.com/search?q=label%3A%22good+first+issue%22+state%3Aopen+is%3Aissue+repo%3Awordpress%2Fopenverse+repo%3Awordpress%2Fopenverse-frontend+repo%3Awordpress%2Fopenverse-api+repo%3Aw
```suggestion
  link: https://github.com/wordpress/openverse/labels/help%20wanted
```

2021-10-01 15:41 UTC, zackkrida commented
Thanks @ritwik12 I've switched to the `help wanted` issues link. Not sure where I would add the shared project board for the repositories, but it is https://github.com/orgs/WordPress/projects/3

2021-10-01 22:36 UTC, ritwik12 commented
@zackkrida If you want to keep the shared project board, that is for the whole WordPress Org. you can either create a new PR for adding the Org with that Project board link or maybe update this one with the link. that's on you.

Three options from my side:

1. **Keep it this way only:** for that please change the link to `https://github.com/WordPress/openverse/labels/help%20wanted`. It means the same but our bots are case sensitive so it will give errors while updating the project stats.
2. **Change the issue link to Project Board:** Keep the site link the same and change the issue link.
3. **Change both site link and issue link:** Either create a separate PR or do this in this one. Change the site link to the WordPress Org link and change the issue link to the project board link.

For 2 and 3, our bot will not be able to update the project stats but we are open to any options which is more useful to you. Please let me know if any doubts.

2021-10-01 22:37 UTC, ritwik12 requested changes
Please update PR with your best suitable option as given.

2021-10-02 13:58 UTC, ritwik12 approved these changes

2021-10-02 13:58 UTC, merged