Introduce Paper
up-for-grabs/up-for-grabs.net pull request #2908
Opened 2021-09-27 19:45 UTC by josharsh

Paper is a cross-platform mobile application that allows scanning documents in real-time.

2021-09-27 23:16 UTC, ritwik12 commented
@josharsh We already added YAWP in #2902. I think your forgot to pull.

2021-09-27 23:17 UTC, ritwik12 requested changes

2021-09-27 23:17 UTC, ritwik12 commented on _data/projects/YAWP.yml
> +---
Already merged in #2902

2021-09-28 06:55 UTC, josharsh commented on _data/projects/YAWP.yml
> +---
Oops

2021-09-28 06:55 UTC, josharsh commented on _data/projects/YAWP.yml
> +---
ACK

2021-09-28 16:27 UTC, ritwik12 approved these changes

2021-09-28 16:27 UTC, merged

2021-09-28 16:27 UTC, ritwik12 commented
@josharsh Thanks!!