Added SentimentAnalyzer project for up for grabs
up-for-grabs/up-for-grabs.net pull request #2918
Opened 2021-10-01 06:50 UTC by arafattehsin

2021-10-01 22:43 UTC, ritwik12 requested changes

2021-10-01 22:43 UTC, ritwik12 commented on SentimentAnalyzer.yml
> +desc: Semantic Analyzer is an on-device (offline) open-source library to find out what customers think of your brand or topic by analyzing raw text for clues about positive or negative sentiment. Thi
@arafattehsin Want to make it a bit short?

2021-10-01 22:45 UTC, ritwik12 commented
@arafattehsin Nice. I once developed a Sentiment Analysis model a couple of years back. Did that using CNN for Sentence This stuff is tough and not enough clean data to train the model.

2021-10-02 01:18 UTC, arafattehsin commented
@ritwik12 Thanks! I just edited the description.

2021-10-02 13:59 UTC, ritwik12 approved these changes

2021-10-02 13:59 UTC, merged

2021-10-03 17:19 UTC, ritwik12 commented
@arafattehsin We reverted this as this was not in _data/projects folder. Please open a new PR.