add cfcfrj-legit-info to up-for-grabs
up-for-grabs/up-for-grabs.net pull request #2985
Opened 2021-11-09 21:03 UTC by demilolu

2021-11-12 19:40 UTC, ritwik12 requested changes

2021-11-12 19:40 UTC, ritwik12 commented on _data/projects/cfcfrj-legit-info.yml
> +name: Call for Code for Racial Justice: Legit-Info
@demilolu  Please remove ":" from the line, being YML it causes issues.

2021-11-12 19:40 UTC, ritwik12 commented on _data/projects/cfcfrj-truth-loop.yml
> +name: Call for Code for Racial Justice: Truth Loop
@demilolu  Please remove ":" from the line, being YML it causes issues.

2021-11-12 19:40 UTC, ritwik12 commented on _data/projects/cfcfrj-legit-info.yml
> +  link: https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info
Need label link here

2021-11-12 19:40 UTC, ritwik12 commented on _data/projects/cfcfrj-truth-loop.yml
> +  link: https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop
Label link please

2022-02-23 14:27 UTC, shiftkey commented
Closing this out due to inactivity. 

@demilolu if you're still interested in adding the project please submit a new pull request and consider the feedback from this discussion.

2022-02-23 14:27 UTC, closed without merging