adding Horusec
up-for-grabs/up-for-grabs.net pull request #3061
Opened 2022-02-03 17:13 UTC by caroldf07

I think my project would be a great fit for Up for Grabs.

Let me know if there's any feedback you have about the template!

2022-02-03 20:15 UTC, ritwik12 requested changes

2022-02-03 20:15 UTC, ritwik12 commented on _data/projects/horusec.yml
> +  issue-count:
You don't need to put these, It gets fetched and appended automatically later.

2022-02-03 20:15 UTC, ritwik12 commented on _data/projects/horusec.yml
> +  link: https://github.com/ZupIT/horusec/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
Please change this to https://github.com/ZupIT/horusec/labels/good%20first%20issue

2022-02-03 20:21 UTC, ritwik12 commented
@caroldf07 Reviewed all your PRs, please make changes. 

Saw your profile. Developer Advocate kinda looks fancy but not sure what that role is. Is it a mix of Developer and Partner engineer types, Consultanting and all?

2022-02-03 20:53 UTC, ritwik12 approved these changes

2022-02-03 20:56 UTC, caroldf07 commented
> @caroldf07 Reviewed all your PRs, please make changes.
> 
> Saw your profile. Developer Advocate kinda looks fancy but not sure what that role is. Is it a mix of Developer and Partner engineer types, Consultanting and all?

Kinda of, kkkk. I'm responsible for make comunity to knows about Zup's open source projects, talk about and receive feeback about them to improve developer's experience using our solutions :)

2022-02-03 20:57 UTC, ritwik12 commented
> > @caroldf07 Reviewed all your PRs, please make changes.
> > Saw your profile. Developer Advocate kinda looks fancy but not sure what that role is. Is it a mix of Developer and Partner engineer types, Consultanting and all?
> 
> Kinda of, kkkk. I'm responsible for make comunity to knows about Zup's open source projects, talk about and receive feeback about them to improve developer's experience using our solutions :)

That's cool, will read blogs on that then, thanks

2022-02-03 20:58 UTC, ritwik12 commented
@caroldf07 CI is falling for all your PRs, please check.

2022-02-03 21:14 UTC, ritwik12 commented
@caroldf07 I guess you pulled and merged. please revert that back to your original yml. CI is failing, will merge your PR once #3064 is solved.

2022-02-03 21:42 UTC, ritwik12 commented
@caroldf07 Please refresh pull once

2022-02-04 13:05 UTC, ritwik12 requested changes

2022-02-04 13:05 UTC, ritwik12 commented on _data/projects/horusec.yml
> +  - CI/CD
@caroldf07 We need to fix these errors, please change names accordingly.

- Tag 'SAST' contains invalid characters. Allowed characters: a-z, 0-9, +, #, . or -
- Tag 'CI/CD' contains invalid characters. Allowed characters: a-z, 0-9, +, #, . or -

2022-02-04 13:08 UTC, ritwik12 commented
@caroldf07 Please follow the same tag names in your other PRs too.

2022-02-04 13:10 UTC, ritwik12 approved these changes

2022-02-04 13:15 UTC, ritwik12 requested changes

2022-02-04 13:15 UTC, ritwik12 commented on _data/projects/horusec.yml
> +  - continuous delivery
```suggestion
  - continuous-integrations
  - continuous-delivery
```

2022-02-04 13:16 UTC, caroldf07 commented on _data/projects/horusec.yml
> +  - continuous delivery
I saw it, I've just removed

2022-02-04 13:17 UTC, ritwik12 approved these changes

2022-02-04 13:21 UTC, merged

2022-02-04 13:21 UTC, ritwik12 commented
@caroldf07 Thanks!!