adding Beagle framework
up-for-grabs/up-for-grabs.net pull request #3063
Opened 2022-02-03 17:26 UTC by caroldf07

I think my project would be a great fit for Up for Grabs.

Let me know if there's any feedback you have about the template!

2022-02-03 20:18 UTC, ritwik12 requested changes

2022-02-03 20:18 UTC, ritwik12 commented on _data/projects/beagle-framework.yml
> +  issue-count:
These lines are not required, please remove.

2022-02-03 20:52 UTC, ritwik12 approved these changes

2022-02-04 13:13 UTC, ritwik12 requested changes

2022-02-04 13:13 UTC, ritwik12 commented on _data/projects/beagle-framework.yml
> +  - reactive native
@caroldf07 No space allowed too, also did you meant react-native?

2022-02-04 13:14 UTC, ritwik12 commented
@caroldf07 Sorry for the trouble but we have kept the tag names generic so that we won't have duplicate ones.

2022-02-04 13:23 UTC, caroldf07 commented
@ritwik12 it's ok, the mistake was mine :)

2022-02-04 13:24 UTC, ritwik12 approved these changes

2022-02-04 13:25 UTC, merged

2022-02-04 13:26 UTC, ritwik12 commented
@caroldf07 Thanks for adding your projects and fixing the issues promptly.