Create TheIdServer.yaml
up-for-grabs/up-for-grabs.net pull request #3153
Opened 2022-03-29 08:08 UTC by aguacongas

# TheIdServer

[OpenID/Connect](https://openid.net/connect/), [OAuth2](https://oauth.net/2/) and [WS-Federation](https://docs.oasis-open.org/wsfed/federation/v1.2/os/ws-federation-1.2-spec-os.html) server based on [IdentityServer4](https://identityserver4.readthedocs.io/en/latest/) or [Duende IdentityServer](https://duendesoftware.com/products/identityserver) needs your help.

2022-03-31 19:08 UTC, ritwik12 requested changes

2022-03-31 19:08 UTC, ritwik12 commented on _data/projects/TheIdServer.yaml
> +site: https://github.com/Aguafrommars/TheIdServer#readme
@aguacongas Please make it https://github.com/Aguafrommars/TheIdServer

2022-04-07 08:49 UTC, aguacongas commented on _data/projects/TheIdServer.yaml
> +site: https://github.com/Aguafrommars/TheIdServer#readme
Done

2022-04-07 08:51 UTC, aguacongas commented
@ritwik12 change done

2022-04-08 19:24 UTC, ritwik12 approved these changes

2022-04-08 19:29 UTC, merged

2022-04-08 19:29 UTC, ritwik12 commented
@aguacongas Thanks!!