Adding Instalution
up-for-grabs/up-for-grabs.net pull request #3260
Opened 2022-07-05 01:54 UTC by groovenectar

The list of TODOs is brief and lives in the `README.md` file here: https://github.com/groovenectar/instalution#short-list-of-needs--todos

2022-07-06 22:54 UTC, groovenectar commented
Is that first test checking for a website link in the Github profile? Is there a way to re-run that?

2022-07-10 07:28 UTC, ritwik12 requested changes

2022-07-10 07:28 UTC, ritwik12 commented on _data/projects/Instalution.yml
> +  name: instalution
@groovenectar This should be the name of a LABEL at your git repo.

2022-07-10 07:28 UTC, ritwik12 commented on _data/projects/Instalution.yml
> +  link: https://github.com/instalution/frontend/blob/master/README-en.md#short-list-of-needs--todos
@groovenectar This should be the link to that LABEL. Eg: https://github.com/instalution/frontend/labels/good%20first%20issue

2022-07-10 17:27 UTC, groovenectar commented on _data/projects/Instalution.yml
> +  name: up-for-grabs
@[ritwik12](https://github.com/ritwik12) Is this the correct format?

2022-07-27 12:34 UTC, ritwik12 approved these changes

2022-07-27 12:37 UTC, merged