Adding Scribe-iOS
up-for-grabs/up-for-grabs.net pull request #3271
Opened 2022-07-13 22:28 UTC by andrewtavis

Hi all 👋 Am hoping to get Scribe-iOS onto Up for Grabs :) I've been working on the project for a bit over half a year at this point, and slowly have been getting contributors. Scribe uses Wikidata as a backend, so I've been in active communication with many at Wikimedia about it, and it's  recently been added to the [featured projects for new Wikimedia developers](https://www.mediawiki.org/wiki/New_Developers). It's still very early on for it, but feedback has been great so far, and I'd love to find contributors for both iOS and the WIP Android version.

Would be happy to hear your all's feedback on adding it, and hope the suggested `.yml` file meets the specifications!

2022-07-27 12:39 UTC, ritwik12 requested changes

2022-07-27 12:39 UTC, ritwik12 commented on _data/projects/scribe-ios.yml
> +  link: https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
@andrewtavis Can you please change this to https://github.com/scribe-org/Scribe-iOS/labels/good%20first%20issue

2022-07-27 13:24 UTC, andrewtavis commented
Thanks for the review, @ritwik12! I just updated the file as directed. Let me know if anything else is needed :)

2022-08-13 06:54 UTC, andrewtavis commented
> This pull request will be closed tomorrow because it has not had recent activity after being reviewed. If you are still interested in adding your project to the site, please submit a new pull request and address the above feedback. Thank you for your contribution!

Hi @ritwik12, if possible could you review this again? I did make the change that you suggested.

2022-08-29 05:39 UTC, ritwik12 approved these changes

2022-08-29 05:40 UTC, merged

2022-08-29 05:40 UTC, ritwik12 commented
@andrewtavis Thanks, sorry for the delay.

2022-08-29 05:50 UTC, andrewtavis commented
Not a problem, @ritwik12 :) Thank you!