adding my new ReactJS project
up-for-grabs/up-for-grabs.net pull request #3595
Opened 2022-11-12 15:16 UTC by pareshwar11

submitted my project repository and live project link.

2022-12-19 11:45 UTC, ritwik12 requested changes

2022-12-19 11:45 UTC, ritwik12 commented on cozy-clothing.yml
> +  - reactJswithfirebaseauthentication
@pareshwar11 Add some common tag please. See other tags in /projects files

2022-12-19 11:45 UTC, ritwik12 commented on cozy-clothing.yml
> +  link: https://github.com/pareshwar11/cozy-clothing-v1-e-commerce
@pareshwar11 This should be the link to above label.

2023-02-10 15:42 UTC, shiftkey commented
Closing this out due to inactivity. 

Feel free to resubmit with a new pull request if this is something that you're interested in completing.

2023-02-10 15:42 UTC, closed without merging