Adding Bagisto here.
up-for-grabs/up-for-grabs.net pull request #3613
Opened 2022-11-18 09:25 UTC by papnoisanjeev

Bagisto Will be great fit for up for grabs.

2022-12-19 11:49 UTC, ritwik12 requested changes

2022-12-19 11:49 UTC, ritwik12 commented on _data/projects/bagisto.yml
> +  link: https://github.com/bagisto/bagisto/issues?q=is%3Aopen+is%3Aissue+label%3AEasy
@papnoisanjeev 
```suggestion
  link: https://github.com/bagisto/bagisto/labels/Easy
```

2022-12-19 11:55 UTC, papnoisanjeev commented on _data/projects/bagisto.yml
> +  link: https://github.com/bagisto/bagisto/issues?q=is%3Aopen+is%3Aissue+label%3AEasy
> @papnoisanjeev

@ritwik12  done.

2023-01-09 06:33 UTC, papnoisanjeev commented
> This pull request will be closed tomorrow because it has not had recent activity after being reviewed. If you are still interested in adding your project to the site, please submit a new pull request and address the above feedback. Thank you for your contribution!

@ritwik12 
We have already done with suggested changes given by you [here](https://github.com/up-for-grabs/up-for-grabs.net/pull/3613/commits/d5aebcfc275ba6e3d8436ca0f0b341281fa26956).

If still anything need to be change please let us know.

2023-01-24 06:47 UTC, Silvrbckw commented
papnoisanjeev:gh-pages

2023-01-31 16:57 UTC, shiftkey approved these changes

2023-02-03 11:03 UTC, merged