Register Cesium C compiler
up-for-grabs/up-for-grabs.net pull request #4091
Opened 2023-08-04 04:19 UTC by kant2002

Add Cesium C compiler which compiles C to IL

2023-08-04 04:24 UTC, kant2002 reviewed
Change tags

2023-08-06 15:29 UTC, kant2002 commented
@shiftkey would it be appropriate to ping you, so you can review PR ?

2023-08-08 21:06 UTC, ritwik12 requested changes, later dismissed

2023-08-08 21:06 UTC, ritwik12 commented on _data/projects/Cesium.yml
> +  - с#
```suggestion
- .net
- compiler
- с
- с#
```

2023-08-23 13:57 UTC, kant2002 commented
@ritwik12 can you please review this again?

2023-08-27 18:27 UTC, shiftkey commented
@kant2002 the reason why this PR was stuck is that the validation wanted an ASCII C character, but your file had some unrecognized characters (this `D181`) sequence:

<img width="674" alt="Screenshot 2023-08-27 at 3 23 01 PM" src="https://github.com/up-for-grabs/up-for-grabs.net/assets/359239/61bee134-829d-4317-9721-160ea78c80e3">

I noticed in VSCode that there was also a warning here about this:


<img width="520" alt="Screenshot 2023-08-27 at 3 26 54 PM" src="https://github.com/up-for-grabs/up-for-grabs.net/assets/359239/07444b79-7914-471b-aa59-a7f1d75a1cdf">

2023-08-27 18:28 UTC, shiftkey commented on _data/projects/Cesium.yml
> +  name: up for grabs
:art: label must match the value used

```suggestion
  name: up-for-grabs
```

2023-08-27 18:30 UTC, shiftkey commented on _data/projects/Cesium.yml
> +  name: up-for-grabs
```suggestion
  name: good-first-issue
```

2023-08-27 18:32 UTC, shiftkey approved these changes

2023-08-27 18:32 UTC, merged