Create Web_Template_NNN
up-for-grabs/up-for-grabs.net pull request #4195
Opened 2023-09-24 15:09 UTC by harry97sharma

2023-09-24 15:11 UTC, harry97sharma reviewed
Forgot to add extension in file

2023-09-25 14:59 UTC, shiftkey requested changes

2023-09-25 14:59 UTC, shiftkey commented on _data/projects/WT_nnn.yml
> +  link: https://github.com/harry97sharma/WEB_TEMPLATE_001/issues?q=label%3A%22help+wanted%22+label%3A%22good+first+issue%22
```suggestion
  name: good first issue
  link: https://github.com/harry97sharma/WEB_TEMPLATE_001/labels/good%20first%20issue
```

2023-09-25 14:59 UTC, shiftkey commented on _data/projects/WT_nnn.yml
> +site: https://example.org/your-project-link-here
:art: this needs to be a real site

2023-09-25 14:59 UTC, shiftkey commented on _data/projects/WT_nnn.yml
> +desc: Cool Colurful Template for easy web development
Please provide a good description here of this project and what contributions you are interested in

2023-09-25 14:59 UTC, shiftkey commented on _data/projects/WT_nnn.yml
> +name: WEB_TEMPLATE_001
This repository is very new, and I'm not sure it's a good fit for being listed here based on the details provided so far

2023-10-16 12:45 UTC, closed without merging

2023-10-16 12:45 UTC, shiftkey commented
Closing this out due to inactivity. Please re-submit if you are still interested and are able to address the feedback above.