Create macalifa.yml
up-for-grabs/up-for-grabs.net pull request #463
Opened 2016-09-22 13:56 UTC by theweavrs

I would like to add my project to `up-for-grabs.net`

2016-09-23 23:43 UTC, shiftkey commented on _data/projects/macalifa.yml
> +- .NET
There's a issue reported in the CI tests - this should be in quote marks.

2016-09-23 23:43 UTC, shiftkey requested changes

2016-09-24 05:52 UTC, theweavrs commented on _data/projects/macalifa.yml
> +- .NET
I added the quote marks for .NET, .NET Core and C# tag. Is that okay?

2016-09-26 03:24 UTC, shiftkey approved these changes

2016-09-26 03:25 UTC, shiftkey commented on _data/projects/macalifa.yml
> +- .NET
@theweavrs :thumbsup:

2016-09-26 03:25 UTC, merged

2016-09-26 03:35 UTC, theweavrs commented on _data/projects/macalifa.yml
> +- .NET
Thank you!