added Blitzed IRC Trivia
up-for-grabs/up-for-grabs.net pull request #473
Opened 2016-10-07 20:08 UTC by andy5995

2016-10-08 04:15 UTC, shiftkey requested changes
Just one little change

2016-10-08 04:15 UTC, shiftkey commented on _data/projects/blitzed-irc-trivia.yml
> +  link: https://github.com/andy5995/blitzed-irc-trivia/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
You can simplify this down to `https://github.com/andy5995/blitzed-irc-trivia/labels/help%20wanted`

2016-10-08 05:27 UTC, andy5995 commented on _data/projects/blitzed-irc-trivia.yml
> +  link: https://github.com/andy5995/blitzed-irc-trivia/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
Thanks for pointing that out

2016-10-08 09:36 UTC, shiftkey approved these changes

2016-10-08 09:36 UTC, shiftkey requested changes

2016-10-08 09:36 UTC, shiftkey commented on _data/projects/blitzed-irc-trivia.yml
> +  name: Blitzed-Irc-Trivia
Oops, missed this one. Make this `help wanted`

2016-10-08 18:25 UTC, andy5995 commented on _data/projects/blitzed-irc-trivia.yml
> +  name: Blitzed-Irc-Trivia
I wonder if I can have the link point to the "Contribution" guidelines page? From there I link to the issues. The last time I had a project listed here, people would ask how to get started, and I'd always have to point them to my "Contributions" page.

2016-10-09 00:45 UTC, shiftkey commented on _data/projects/blitzed-irc-trivia.yml
> +  name: Blitzed-Irc-Trivia
@andy5995 Mind opening an issue to discuss this further? Perhaps there's some different fields we can capture here if maintainers want to send users down a different path.

2016-10-09 00:46 UTC, shiftkey approved these changes

2016-10-09 00:46 UTC, merged

2016-10-09 00:56 UTC, andy5995 commented on _data/projects/blitzed-irc-trivia.yml
> +  name: Blitzed-Irc-Trivia
Thanks for the merge. No, I don't mind opening up a ticket, thanks for the response.