adds a contributor guideline link above the issues, as per suggestion…
up-for-grabs/up-for-grabs.net pull request #487
Opened 2016-10-26 03:01 UTC by ckhatri

… at issue #476 

Added some css styling on font size, went with a font size of 14px.
The contributor guideline link will only show up if the .yml file has a contribute: link, so it's optional. 

I didn't use the GitHub Api for existing projects but that might be something I do later.

Hope everything checks out, let me know!

2016-10-30 21:40 UTC, shiftkey commented
@ckhatri i like where this is heading. I tested it out with a project to see how it would render:

<img width="710" src="https://cloud.githubusercontent.com/assets/359239/19840219/95a89d30-9eae-11e6-9b77-4159a4df1873.png">

Could we put this below the label? And maybe make it visually different to the label element?

2016-11-01 19:42 UTC, ckhatri commented
Yup! Will get that done this weekend.

2017-02-27 21:05 UTC, ckhatri commented
uh better late than never?

2017-04-15 22:58 UTC, shiftkey requested changes
This is close - at this point I'm just thinking about whether we can style that better.

2017-04-15 22:58 UTC, shiftkey commented on stylesheets/stylesheet.css
> +  word-break: break-all;
There's some weird trimming here:

<img width="765" src="https://cloud.githubusercontent.com/assets/359239/25067296/27e09246-2282-11e7-89f3-729d001350e5.png">

Should this be `keep-all`?

2017-04-15 22:58 UTC, shiftkey commented on _includes/scripts.html
> +       <% if (project.contribute) { %>
Could you add this field to the example payload in the `README.md`?

2019-02-11 19:14 UTC, shiftkey commented
Closing this out due to inactivity.

@ckhatri if you're still interested in implementing this, please open a fresh pull request

2019-02-11 19:14 UTC, closed without merging