Issue #547 - Reformat JavaScript files
up-for-grabs/up-for-grabs.net pull request #550
Opened 2017-02-07 16:52 UTC by bigwave

Simple 'Auto Format' in Visual Studio Code with the 'EditorConfig For VS Code' extension installed and the existing .editorconfig file.

Now you can have 'auto format on save/paste' configured and not have to worry about massive changes

2017-02-07 17:02 UTC, shiftkey requested changes
Changes look good, aside from that one off line that's probably a syntax error...

2017-02-07 17:02 UTC, shiftkey commented on javascripts/main.js
> +  projectsPanel = null;
This seems off. Previous line probably needs a `,`

2017-02-08 16:51 UTC, bigwave commented
Fixed the syntax error...

2017-02-08 17:39 UTC, shiftkey approved these changes

2017-02-08 17:39 UTC, merged

2017-02-08 17:40 UTC, shiftkey commented
@bigwave fantastic, thanks for that!