Create bike_md.yml
up-for-grabs/up-for-grabs.net pull request #618
Opened 2017-05-13 20:44 UTC by Josiah-DuBose

Hello, 
BikeMD is a new open source project. There is lots of work to be done so I'll be adding a lot more issues soon!

2017-05-14 08:44 UTC, shiftkey requested changes
Looking good, just a couple of suggestions to clean this up.

2017-05-14 08:44 UTC, shiftkey commented on bike_md.yml
> +  link: *https://github.com/bike-md/bike_md/issues*
Make this `https://github.com/bike-md/bike_md/issues/labels/up%20for%20grabs`

2017-05-14 08:44 UTC, shiftkey commented on bike_md.yml
> +name: *BikeMD*
No need to wrap these values in `*`

2017-05-15 11:44 UTC, Josiah-DuBose commented
Done!

2017-05-15 11:48 UTC, shiftkey commented
@Josiah-DuBose thanks!

2017-05-15 11:48 UTC, merged