Create docusaurus.yml
up-for-grabs/up-for-grabs.net pull request #944
Opened 2018-06-07 16:48 UTC by endiliey

2018-06-07 20:15 UTC, ritwik12 requested changes

2018-06-07 20:15 UTC, ritwik12 commented on _data/projects/docusaurus.yml
> +  name: good first contribution
@endiliey Your label name and the label link are not for each other, is it fine this way?

2018-06-08 13:06 UTC, endiliey commented
@ritwik12 done :)

2018-06-08 22:59 UTC, ritwik12 approved these changes

2018-06-08 22:59 UTC, merged

2018-06-08 22:59 UTC, ritwik12 commented
@endiliey Thanks!!