Create CommonIntents.yml
up-for-grabs/up-for-grabs.net pull request #947
Opened 2018-06-09 19:05 UTC by JanStoltman

Create new 'CommonIntents.yml' with data about Common Intents project

2018-06-13 18:34 UTC, ritwik12 requested changes

2018-06-13 18:34 UTC, ritwik12 commented on _data/projects/CommonIntents.yml
> +  link: https://github.com/JanStoltman/CommonIntents/issues
@JanStoltman Please mention the link to the issues related to your label here, Also do add some issues so that others could contribute.

2018-06-14 06:28 UTC, ritwik12 approved these changes

2018-06-14 06:28 UTC, merged

2018-06-14 06:28 UTC, ritwik12 commented
@JanStoltman Thanks!!

2018-06-14 06:29 UTC, ritwik12 commented
@JanStoltman Do add some issues so that others could contribute.

2018-06-14 16:17 UTC, JanStoltman commented
I've added some initial issues. I will expand this list as the library grows and more specific tasks emerge.

2018-06-14 18:51 UTC, ritwik12 commented
@JanStoltman Great.