add project Cover Letter Snippets to up-for-grabs projects.
up-for-grabs/up-for-grabs.net pull request #976
Opened 2018-07-31 21:52 UTC by mattcheah

2018-08-07 19:17 UTC, ritwik12 commented
@mattcheah You have not mentioned any language in tags, is it correct?

2018-08-08 15:34 UTC, mattcheah commented
Hi @ritwik12, my apologies, i forgot to do this. I have changed it now, thanks!

2018-08-09 11:33 UTC, ritwik12 requested changes

2018-08-09 11:33 UTC, ritwik12 commented on _data/projects/cover-letter-snippets.yml
> +  link: https://github.com/mattcheah/cover-letter-snippets/issues
@mattcheah Please mention the link to your label.

2018-08-10 11:58 UTC, ritwik12 approved these changes

2018-08-10 11:58 UTC, merged

2018-08-10 11:58 UTC, ritwik12 commented
@mattcheah Thanks!!